# Generated by Django 4.2.4 on 2023-08-06 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 6)),
        ),
    ]
