# Generated by Django 4.2.4 on 2023-08-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_user_info_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 16, 40, 35, 818058)),
        ),
    ]
