# Generated by Django 4.2.4 on 2023-08-06 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_user_info_date_alter_user_info_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 22, 56, 21, 932162)),
        ),
    ]
